### ISSUE TITLE
Exception displaying help when script name is quite long

### ISSUE THREAD

**Issue by k7sleeper** [nodeca/argparse#86]
Having a long script name like `extract-display-actions-from-action-provider-log-file` I get the following exception when using help option:

```
extract-display-actions-from-action-provider-log-file.coffee -h
TypeError: parts.forEach is not a function
  at _getLines (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\help\formatter.js:378:15)
  at HelpFormatter._formatUsage (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\help\formatter.js:416:17)
  at D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\help\formatter.js:66:17
  at Array.map (native)
  at Section.formatHelp (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\help\formatter.js:60:26)
  at HelpFormatter.formatHelp (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\help\formatter.js:299:32)
  at ArgumentParser.formatUsage (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\argument_parser.js:1035:20)
  at ArgumentParser.printUsage (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\argument_parser.js:1091:27)
  at ArgumentParser.error (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\argument_parser.js:1167:8)
  at ArgumentParser.parseKnownArgs (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\argument_parser.js:297:10)
  at ArgumentParser.parseArgs (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\node_modules\argparse\lib\argument_parser.js:234:21)
  at Object.res.process (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\impl\extract-display-actions-from-action-provider-log-file\cli.j
s:73:24)
  at Object.<anonymous> (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\extract-display-actions-from-action-provider-log-file.coffee:24:
12)
  at Object.<anonymous> (D:\dev\svn\working-copies\ips\ips-cki-web-ui\tools\extract-display-actions-from-action-provider-log-file.coffee:2:1
)
  at Module._compile (module.js:398:26)
  at Object.exports.run (d:\dev\lng\JavaScript\node-globals\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (d:\dev\lng\JavaScript\node-globals\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (d:\dev\lng\JavaScript\node-globals\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (d:\dev\lng\JavaScript\node-globals\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (d:\dev\lng\JavaScript\node-globals\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:398:26)
  at Object.Module._extensions..js (module.js:405:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at startup (node.js:141:18)
  at node.js:980:3
```

**Comment by rlidwka** [comment]
fixed in argparse 2.0
